# Makefile template for codeforces contest
# Bartłomiej Najdecki, 2015

Flags = -Wall -Wundef -pedantic -pedantic-errors -std=c++11
CPP = g++


a : Makefile a.cpp
	$(CPP) $(Flags) -o a a.cpp
b : Makefile b.cpp
	$(CPP) $(Flags) -o b b.cpp
c : Makefile c.cpp
	$(CPP) $(Flags) -o c c.cpp
d : Makefile d.cpp
	$(CPP) $(Flags) -o d d.cpp
e : Makefile e.cpp
	$(CPP) $(Flags) -o e e.cpp
